stages:
  - validate
  - cost-estimate
  - build
  - deploy

variables:
  AWS_DEFAULT_REGION: "$AWS_REGION"
  AWS_ACCESS_KEY_ID: "$AWS_ACCESS_KEY_ID"
  AWS_SECRET_ACCESS_KEY: "$AWS_SECRET_ACCESS_KEY"
  PACKER_VERSION: "1.10.0"
  # Cost estimation variables (USD per hour in us-east-1)
  T3_NANO_COST: "0.0052"
  T3_MICRO_COST: "0.0104"
  T3_SMALL_COST: "0.0208"
  T3_MEDIUM_COST: "0.0416"
  T3_LARGE_COST: "0.0832"
  T3_XLARGE_COST: "0.1664"
  T3_2XLARGE_COST: "0.3328"
  ESTIMATED_BUILD_TIME_MINUTES: "30"

validate_packer:
  stage: validate
  image: hashicorp/packer:latest
  tags:
    - homelab
    - local
  script:
    - echo "Validating Packer template..."
    - packer init .
    - packer validate -var-file="variables.pkrvars.hcl" packer.pkr.hcl
    - echo "Packer template validation completed successfully"
  only:
    - main
    - develop

cost_estimate:
  stage: cost-estimate
  image: alpine:latest
  tags:
    - homelab
    - local
  before_script:
    - apk add --no-cache bash bc
  script:
    - |
      echo "=== AWS AMI Build Cost Estimation ==="
      
      # Read instance type from variables file
      INSTANCE_TYPE=$(grep 'instance_type' variables.pkrvars.hcl | cut -d'"' -f2)
      echo "Instance Type: $INSTANCE_TYPE"
      
      # Determine hourly cost based on instance type
      case $INSTANCE_TYPE in
        "t3.nano")    HOURLY_COST=$T3_NANO_COST ;;
        "t3.micro")   HOURLY_COST=$T3_MICRO_COST ;;
        "t3.small")   HOURLY_COST=$T3_SMALL_COST ;;
        "t3.medium")  HOURLY_COST=$T3_MEDIUM_COST ;;
        "t3.large")   HOURLY_COST=$T3_LARGE_COST ;;
        "t3.xlarge")  HOURLY_COST=$T3_XLARGE_COST ;;
        "t3.2xlarge") HOURLY_COST=$T3_2XLARGE_COST ;;
        *)             HOURLY_COST="0.0416" ; echo "Unknown instance type, using t3.medium cost" ;;
      esac
      
      # Calculate total estimated cost
      BUILD_TIME_HOURS=$(echo "scale=4; $ESTIMATED_BUILD_TIME_MINUTES / 60" | bc)
      TOTAL_COST=$(echo "scale=4; $HOURLY_COST * $BUILD_TIME_HOURS" | bc)
      
      echo "Estimated Hourly Cost: \$$HOURLY_COST USD"
      echo "Estimated Build Time: $ESTIMATED_BUILD_TIME_MINUTES minutes ($BUILD_TIME_HOURS hours)"
      echo "Total Estimated Cost: \$$TOTAL_COST USD"
      echo "AWS Region: $AWS_DEFAULT_REGION"
      echo "================================="
      
      # Export for use in other jobs - ensure file is created
      echo "INSTANCE_TYPE=$INSTANCE_TYPE" > cost_estimate.env
      echo "HOURLY_COST=$HOURLY_COST" >> cost_estimate.env
      echo "TOTAL_COST=$TOTAL_COST" >> cost_estimate.env
      
      # Verify file exists and show contents
      ls -la cost_estimate.env || echo "File not found!"
      echo "File contents:"
      cat cost_estimate.env || echo "Cannot read file!"
      echo "File size: $(wc -c < cost_estimate.env) bytes"
  artifacts:
    paths:
      - cost_estimate.env
    expire_in: 1 hour
  only:
    - main
    - develop

build_ami:
  stage: build
  image: hashicorp/packer:latest
  tags:
    - homelab
    - local
  timeout: 45m
  script:
    - echo "Building AWS AMI with Packer..."
    - packer init .
    - packer build -var-file="variables.pkrvars.hcl" packer.pkr.hcl
    - echo "AMI build completed successfully"
  artifacts:
    reports:
      dotenv: build.env
    paths:
      - packer-manifest.json
    expire_in: 1 week
  only:
    - main
    - develop

deploy_verify:
  stage: deploy
  image: amazon/aws-cli:latest
  tags:
    - homelab
    - local
  script:
    - echo "Verifying AMI deployment..."
    - aws ec2 describe-images --owners self --region $AWS_DEFAULT_REGION --query 'Images[?starts_with(Name, `ubuntu-24-04-lts-prod`)].{Name:Name,ImageId:ImageId,CreationDate:CreationDate}' --output table
    - echo "AMI verification completed"
  dependencies:
    - build_ami
  only:
    - main
    - develop
