stages:
  - validate
  - build
  - deploy

variables:
  AWS_DEFAULT_REGION: "$AWS_REGION"
  AWS_ACCESS_KEY_ID: "$AWS_ACCESS_KEY_ID"
  AWS_SECRET_ACCESS_KEY: "$AWS_SECRET_ACCESS_KEY"
  PACKER_VERSION: "1.10.0"

validate_packer:
  stage: validate
  image: hashicorp/packer:latest
  tags:
    - homelab
    - local
  script:
    - echo "Validating Packer template..."
    - packer init .
    - packer validate -var-file="variables.pkrvars.hcl" ubuntu-24-04-lts.pkr.hcl
    - echo "Packer template validation completed successfully"
  only:
    - main
    - develop

build_ami:
  stage: build
  image: hashicorp/packer:latest
  tags:
    - homelab
    - local
  timeout: 45m
  script:
    - echo "Building AWS AMI with Packer..."
    - packer init .
    - packer build -var-file="variables.pkrvars.hcl" ubuntu-24-04-lts.pkr.hcl
    - echo "AMI build completed successfully"
  artifacts:
    reports:
      dotenv: build.env
    paths:
      - packer-manifest.json
    expire_in: 1 week
  when: manual
  only:
    - main
    - develop

deploy_verify:
  stage: deploy
  image: amazon/aws-cli:latest
  tags:
    - homelab
    - local
  script:
    - echo "Verifying AMI deployment..."
    - aws ec2 describe-images --owners self --region $AWS_DEFAULT_REGION --query 'Images[?starts_with(Name, `ubuntu-24-04-lts-prod`)].{Name:Name,ImageId:ImageId,CreationDate:CreationDate}' --output table
    - echo "AMI verification completed"
  dependencies:
    - build_ami
  when: manual
  only:
    - main
    - develop
