stages:
  - build
  - test
  - deploy

build-job:
  stage: build
  script:
    - echo "Building project..."
    - echo "Build complete."

unit-test-job:
  stage: test
  script:
    - echo "Running tests..."
    - echo "Tests completed."

deploy-job:
  stage: deploy
  script:
    - echo "Deploying..."
    - echo "Deployment successful."
