# =====================================================
# GitLab CI Pipeline for Ubuntu AMI Builder
# =====================================================

stages:
  - validate
  - build
  - deploy

variables:
  # Packer configuration
  PACKER_LOG: "1"
  PACKER_CONFIG_FILE: "variables.pkrvars.hcl"
  PACKER_TEMPLATE: "packer.pkr.hcl"
  
  # Docker image for Packer
  PACKER_IMAGE: "hashicorp/packer:latest"

# Validate Packer configuration
validate-job:
  stage: validate
  image: $PACKER_IMAGE
  tags:
    - homelab
    - local
  before_script:
    - echo "🔧 Setting up environment..."
    - echo "AWS Region:" $AWS_DEFAULT_REGION
    - echo "Packer version:"
    - packer version
  script:
    - echo "✅ Validating Packer configuration..."
    - packer validate \
        -var "aws_region=$AWS_DEFAULT_REGION" \
        -var-file="$PACKER_CONFIG_FILE" \
        "$PACKER_TEMPLATE"
    - echo "🎉 Configuration is valid!"
  only:
    - main
    - merge_requests

# Build the AMI
build-job:
  stage: build
  image: $PACKER_IMAGE
  tags:
    - homelab
    - local
  script:
    - echo "🏗️ Building Ubuntu AMI..."
    - packer build \
        -var "aws_region=$AWS_DEFAULT_REGION" \
        -var-file="$PACKER_CONFIG_FILE" \
        "$PACKER_TEMPLATE"
    - echo "🎉 AMI build completed successfully!"
  artifacts:
    reports:
      junit: packer-build-report.xml
    paths:
      - "*.log"
    expire_in: 1 week
  only:
    - main
  when: manual  # Manual trigger for cost control

# Deploy/Report stage
deploy-job:
  stage: deploy
  image: alpine:latest
  tags:
    - homelab
    - local
  script:
    - echo "AMI deployment completed successfully!"
    - echo "Check your AWS EC2 console for the new AMI"
  only:
    - main
  dependencies:
    - build-job

# Optional: Cleanup old AMIs (commented out for safety)
# cleanup-job:
#   stage: deploy
#   image: alpine:latest
#   before_script:
#     - apk add --no-cache aws-cli
#   script:
#     - echo "🧹 Cleaning up old AMIs..."
#     - echo "Customize the cleanup logic as needed"
#   only:
#     - main
#   when: manual
