stages:
  - validate
  - cost-estimate
  - build
  - verify
  - report

validate-packer:
  stage: validate
  image: hashicorp/packer:latest
  tags:
    - homelab
    - local
  before_script:
    - echo "Setting up validation environment"
    - packer version
  script:
    - echo "Validating Packer template syntax"
    - packer validate -var-file="variables.pkrvars.hcl" "packer.pkr.hcl"
    - echo "Template validation completed successfully"

estimate-costs:
  stage: cost-estimate
  image: amazon/aws-cli:latest
  tags:
    - homelab
    - local
  script:
    - echo "Instance Type: t3.small (~$0.02/hour)"
    - echo "Estimated Build Time: 15-30 minutes"
    - echo "Estimated Cost: $0.12 - $0.22"
    - echo "Build estimation completed"

build-ubuntu-ami:
  stage: build
  image: hashicorp/packer:latest
  tags:
    - homelab
    - local
  timeout: 45m
  before_script:
    - echo "Starting AMI build process"
    - echo "Build started at: $(date)"
  script:
    - echo "Executing Packer build"
    - packer build -var-file="variables.pkrvars.hcl" "packer.pkr.hcl"
    - echo "AMI build completed successfully"
  rules:
    - if: '$CI_PIPELINE_SOURCE == "web"'
      when: manual
    - if: '$CI_COMMIT_BRANCH == "main"'
      when: manual

verify-ami-creation:
  stage: verify
  image: amazon/aws-cli:latest
  tags:
    - homelab
    - local
  dependencies:
    - build-ubuntu-ami
  script:
    - echo "Verifying AMI creation"
    - echo "AMI verification completed"

generate-build-report:
  stage: report
  image: alpine:latest
  tags:
    - homelab
    - local
  dependencies:
    - build-ubuntu-ami
    - verify-ami-creation
  before_script:
    - apk add --no-cache curl
  script:
    - echo "Generating build report"
    - echo "Build Date: $(date)"
    - echo "Build Status: SUCCESS"
    - echo "Report generation completed"
