# .gitlab-ci.yml - Deployment pipeline for packer-ami-generator-v1 project

variables:
  TEMP_DIR: "generated"
  BUILD_SCRIPT: "scripts/build.sh"
  ANSIBLE_PLAYBOOK: "ansible/playbook.yml"

# Dynamic environment mapping
.set_environment: &set_environment
  - |
    if [[ "$CI_COMMIT_REF_NAME" == "main" ]]; then
      export ENVIRONMENT="dev"
    elif [[ "$CI_COMMIT_REF_NAME" == "staging" ]]; then
      export ENVIRONMENT="staging"
    elif [[ "$CI_COMMIT_REF_NAME" == "prod" ]]; then
      export ENVIRONMENT="prod"
    else
      export ENVIRONMENT="dev"  # Default fallback
    fi
    echo "Branch: $CI_COMMIT_REF_NAME -> Environment: $ENVIRONMENT"

stages:
  - validate
  - build
  - deploy

validate-job:
  stage: validate
  script:
    - *set_environment
    - echo "Validating Packer configuration for environment: $ENVIRONMENT"
    - chmod +x $BUILD_SCRIPT
    - ./$BUILD_SCRIPT $ENVIRONMENT validate
  only:
    - main
    - staging
    - prod

build-job:
  stage: build
  script:
    - *set_environment
    - echo "Building AMI or Docker images for environment: $ENVIRONMENT"
    - ./$BUILD_SCRIPT $ENVIRONMENT build
  only:
    - main
    - staging
    - prod
  needs:
    - validate-job
  artifacts:
    paths:
      - packer_cache/
      - builds/
      - "*.log"
    expire_in: 1 week
    when: always

deploy-job:
  stage: deploy
  script:
    - *set_environment
    - echo "Running Ansible deployment for environment: $ENVIRONMENT"
    - ansible-playbook -i inventories/$ENVIRONMENT $ANSIBLE_PLAYBOOK
  when: manual
  only:
    - main
    - staging
    - prod
  needs:
    - build-job

